const React = window.React;
import { Icon } from "../../components/Icon.jsx";

export function DashboardScreen({ user, isGuest, history = [], onStartInterview, onOpenPastReport, onSetupInterview, onOpenPanel }) {
  const name = isGuest ? "there" : user?.name?.split(" ")[0] || "there";
  const answers = history.reduce((sum, item) => sum + (item.questions_answered || 0), 0);
  const subjects = new Set(history.map(item => item.topic)).size;
  return <main className="wrap overview-page">
    <div className="page-intro"><div><span className="eyebrow">YOUR NEXT CHAPTER</span><h1>Let's make you interview-ready.</h1><p className="muted">Hey {name}, one good practice session can change your next conversation.</p></div><button className="btn btn-secondary" onClick={onSetupInterview}><Icon name="contact-round" size={17}/> My profile</button></div>
    <section className="studio-hero">
      <div className="studio-hero-copy"><span className="hero-kicker"><Icon name="sparkles" size={16}/> YOUR SPACE TO GET BETTER</span><h2>Big ambitions.<br/>Better preparation.</h2><p>Find the gaps. Tell your story. Walk into your next interview with more confidence.</p><button className="btn btn-lime" onClick={onStartInterview}>Start practicing <Icon name="arrow-up-right" size={19}/></button><span className="hero-footnote">Your pace. Your progress.</span></div>
      <div className="studio-hero-art"><img src="/Images/interview-desk.png" alt="A sculptural laptop and conversation tools on a desk"/><span className="art-caption"><Icon name="check-check" size={17}/> Practice with purpose</span></div>
    </section>
    <div className="overview-stats">{[["message-circle",answers,"Questions practiced","Knowledge practice"],["book-open",subjects,"Subjects explored","Across your saved interviews"],["history",history.length,"Interview sessions","With evaluated answers"]].map(([icon,count,label,hint]) => <div className="stat-tile" key={label}><span className="stat-icon"><Icon name={icon}/></span><div><span className="stat-value">{count}</span><strong>{label}</strong><small>{hint}</small></div></div>)}</div>
    <div className="section-title"><div><span className="eyebrow">TWO WAYS TO PREPARE</span><h2>What would you like to work on?</h2></div><span className="small muted">Different skills. One goal.</span></div>
    <div className="practice-modes">
      <section className="practice-mode knowledge-mode"><div className="mode-heading"><span className="mode-icon"><Icon name="book-open" size={24}/></span><span className="mode-label">BUILD YOUR FOUNDATION</span></div><h3>Know it. Explain it.</h3><p>Practice core CS concepts and understand the reasoning behind every evaluation.</p><div className="mode-tags"><span>6 CS subjects</span><span>Source-backed feedback</span></div><button onClick={onStartInterview}>Explore knowledge practice <Icon name="arrow-right" size={19}/></button></section>
      <section className="practice-mode persona-mode"><div className="mode-heading"><span className="mode-icon"><Icon name="audio-lines" size={24}/></span><span className="mode-label">PUT YOURSELF IN THE ROOM</span></div><h3>Your story. Meet the panel.</h3><p>Discuss your skills and projects with technical, project and hiring interviewer personas.</p><div className="mode-tags"><span>Resume-aware</span><span>Voice or text</span></div><button onClick={onOpenPanel}>Meet your AI panel <Icon name="arrow-right" size={19}/></button></section>
    </div>
    <div className="overview-bottom"><section className="recent-sessions"><div className="section-title"><h2>Pick up your progress</h2><span className="small muted">Knowledge practice</span></div>
      {!history.length ? <div className="empty-studio"><span className="empty-studio-icon"><Icon name="history" size={30}/></span><h3>Your first session is a fresh start.</h3><p>Your questions, feedback and next steps will appear here.</p><button className="btn btn-secondary" onClick={onStartInterview}>Start your first interview <Icon name="arrow-right" size={16}/></button></div> : <div className="recent-list">{history.slice(0,4).map(row => <button key={row.interview_id} onClick={() => onOpenPastReport(row.interview_id)}><span className="stat-icon"><Icon name="book-open"/></span><span><strong>{row.topic}</strong><small>{row.created_at?.slice(0,10)} · {row.questions_answered || 0} answers</small></span><Icon name="arrow-up-right" size={18}/></button>)}</div>}
    </section><aside className="prep-path"><span className="eyebrow">A SIMPLE WAY FORWARD</span><h2>Your preparation path</h2>{[["01","Make it personal","Set your role and add your experience.",onSetupInterview],["02","Strengthen the basics","Practice concepts and close the gaps.",onStartInterview],["03","Bring it all together","Put your answers in front of the panel.",onOpenPanel]].map(([number,title,detail,action]) => <button key={number} onClick={action}><span>{number}</span><div><strong>{title}</strong><small>{detail}</small></div><Icon name="chevron-right" size={16}/></button>)}</aside></div>
    {isGuest && <p className="guest-footnote"><Icon name="shield-check" size={16}/> You're in a guest workspace. Your saved practice is linked to this browser session.</p>}
  </main>;
}
